apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-analysis
spec:
  metrics:
  - name: success-rate
    successCondition: "result >= 80"
    provider:
      prometheus:
        address: http://prometheus-server.prometheus.svc.cluster.local:9090
        query: |
          100 * (sum(rate(http_requests_total{job="color-grid",status!~"5.."}[1m])) / sum(rate(http_requests_total{job="color-grid"}[1m])))
