apiVersion: v1
kind: Service
metadata:
  name: color-grid-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  selector:
    app: color-grid
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
